# Generated by Django 6.0.6 on 2026-06-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_color',
            field=models.CharField(default='#2081C3', max_length=7),
        ),
    ]
