# Generated by Django 6.0.6 on 2026-06-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background_color',
            field=models.CharField(default='#F7F9F9', max_length=7),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/default.png', upload_to='event_images/'),
        ),
    ]
